table d_products
	lineageTag: a744fb8c-d44b-4045-9c6b-1a9681523432

	column product_id
		dataType: string
		lineageTag: 0e70ef7e-412c-4677-9a99-e642074433e4
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_category_name
		dataType: string
		lineageTag: 738228f7-d4ae-423e-86ea-d0ca8c56a6f8
		summarizeBy: none
		sourceColumn: product_category_name

		annotation SummarizationSetBy = Automatic

	column product_name_lenght
		dataType: int64
		formatString: 0
		lineageTag: 51943c68-e555-4c34-820c-d6c9e1669759
		summarizeBy: none
		sourceColumn: product_name_lenght

		annotation SummarizationSetBy = Automatic

	column product_description_lenght
		dataType: int64
		formatString: 0
		lineageTag: 1192e8b1-4944-48cd-b59a-6e577ace3960
		summarizeBy: none
		sourceColumn: product_description_lenght

		annotation SummarizationSetBy = Automatic

	column product_photos_qty
		dataType: int64
		formatString: 0
		lineageTag: e6bcb26b-524f-43dc-99d1-ea0cae87bb73
		summarizeBy: none
		sourceColumn: product_photos_qty

		annotation SummarizationSetBy = Automatic

	column product_weight_g
		dataType: int64
		formatString: 0
		lineageTag: 24e9c4db-e2f8-41a3-b771-5ac923dd097a
		summarizeBy: none
		sourceColumn: product_weight_g

		annotation SummarizationSetBy = Automatic

	column product_length_cm
		dataType: int64
		formatString: 0
		lineageTag: 0e91175e-9fe5-4202-9bb8-181f39ca8738
		summarizeBy: none
		sourceColumn: product_length_cm

		annotation SummarizationSetBy = Automatic

	column product_height_cm
		dataType: int64
		formatString: 0
		lineageTag: c0b596df-ebd7-4d3b-8c6c-2b41434e4d0e
		summarizeBy: none
		sourceColumn: product_height_cm

		annotation SummarizationSetBy = Automatic

	column product_width_cm
		dataType: int64
		formatString: 0
		lineageTag: 9041553d-c4a6-4cbf-8083-6b1f0ffc50cc
		summarizeBy: none
		sourceColumn: product_width_cm

		annotation SummarizationSetBy = Automatic

	partition d_products = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(Pasta&"olist_products_dataset.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"product_id", type text}, {"product_category_name", type text}, {"product_name_lenght", Int64.Type}, {"product_description_lenght", Int64.Type}, {"product_photos_qty", Int64.Type}, {"product_weight_g", Int64.Type}, {"product_length_cm", Int64.Type}, {"product_height_cm", Int64.Type}, {"product_width_cm", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

