table f_order_payments
	lineageTag: d91cf528-0734-4519-bdf9-2d60f9d88ca4

	column order_id
		dataType: string
		lineageTag: 5eade057-fd26-43f8-ac7f-37309ad6f629
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column payment_sequential
		dataType: string
		lineageTag: 2a67399d-b83b-4388-893c-9c36e42c32a9
		summarizeBy: none
		sourceColumn: payment_sequential

		annotation SummarizationSetBy = Automatic

	column payment_type
		dataType: string
		lineageTag: 482339cd-c055-4967-8050-f948bcf9afd2
		summarizeBy: none
		sourceColumn: payment_type

		annotation SummarizationSetBy = Automatic

	column payment_installments
		dataType: int64
		formatString: 0
		lineageTag: ccc7a9f8-115e-44a4-bad3-a394be06a590
		summarizeBy: sum
		sourceColumn: payment_installments

		annotation SummarizationSetBy = Automatic

	column payment_value
		dataType: double
		lineageTag: 16245109-7fd5-4f21-9675-99a0fc8167b8
		summarizeBy: sum
		sourceColumn: payment_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition f_order_payments = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents(Pasta&"olist_order_payments_dataset.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Valor Substituído" = Table.ReplaceValue(#"Cabeçalhos Promovidos",".",",",Replacer.ReplaceText,{"payment_value"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Valor Substituído",{{"order_id", type text}, {"payment_sequential", type text}, {"payment_type", type text}, {"payment_installments", Int64.Type}, {"payment_value", type number}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

